### PR TITLE
Enable optional TLS

### PR DESCRIPTION
**Pull request by josh-padnick**
I needed to use this tool with a Schema Registry cluster listening on HTTPS, so I added optional support for TLS connections. Note that it's the responsibility of the caller to specify a TLS configuration, as demonstrated in the README changes. As long as users were using the `NewClient` function to create a new Schema Registry client, this change should be fully backwards-compatible.

Note that I did not add any additional tests to validate TLS functionality but I manually validated these changes for use with my own project. Automated tests would require mocking a TLS endpoint, which we ([Gruntwork](https://gruntwork.io])) do in the Schema Registry Terraform module we're writing, but which would be non-trivial here.

'cc @brikis98 @mcalhoun

---
This change is [Reviewable](https://reviewable.io/reviews/landoop/schema-registry/10)

### CODE REVIEW

**Comment by josh-padnick** [comment]
Hi guys, can I get a response on this PR?

**Comment by rollulus** [comment]
@andmarios @stheppi

**Comment by johntdyer** [comment]
@rollulus  / @andmarios  / @stheppi  any change we can get this merged?

**Comment by rollulus** [comment]
I don't have the rights to do so :woman_shrugging: that's why I pinged the other guys

**Comment by johntdyer** [comment]
Gotcha... hey other guys 😉... any thoughts on merging this ?

**Pull request merged**
